name: Build Logic App

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package
      run: (cd src/LogicAppsStandardDemo; mkdir -p ../../output; zip -r ../../output/workflow.zip .)
    - name: Upload Package
      uses: actions/upload-artifact@v2
      with:
        name: workflow
        path: ./output/
        retention-days: 1

  deploy-dev:
    name: Deploy in Dev
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: dev
    env:
      NAME: dev
      LA_NAME: mysamplelogicapp-dev
      RG: logicapp-dev
      LOCATION: eastus
    steps:
    - name: Checkout
      uses: actions/checkout@v1    
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: Create Resource Group
      uses: azure/CLI@v1
      with:
        inlineScript: |
          if [ $(az group exists --name ${{ env.RG }}) = false ]; then
              az group create --name ${{ env.RG }} --location ${{ env.LOCATION }} --tags Environment=${{ env.NAME }}
          fi

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%dT%H%M%S')"

    # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.RG }}
        deploymentName: azure-${{ env.NAME }}-${{ steps.date.outputs.date }}
        template: ./src/ArmTemplates/azure.json
        parameters: name=${{ env.LA_NAME }} environmentName=${{ env.NAME }}

    - uses: actions/download-artifact@master
      with:
        name: workflow
        path: ./output/

    - name: Get publish Profile
      id: publishprofile
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{ env.RG }} `
              -Name ${{ env.LA_NAME }}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest

    - name: Deploy to Azure Logic App
      uses: Azure/functions-action@v1.3.1
      id: la
      with:
        app-name: ${{ env.LA_NAME }}
        package: './output/workflow.zip'
        publish-profile: ${{steps.publishprofile.outputs.profile}}


  deploy-prd:
    name: Deploy in Production
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    environment:
      name: prd
    env:
      NAME: prd
      LA_NAME: mysamplelogicapp-prd
      RG: logicapp-prd
      LOCATION: eastus
    steps:
    - name: Checkout
      uses: actions/checkout@v1    
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: Create Resource Group
      uses: azure/CLI@v1
      with:
        inlineScript: |
          if [ $(az group exists --name ${{ env.RG }}) = false ]; then
              az group create --name ${{ env.RG }} --location ${{ env.LOCATION }} --tags Environment=${{ env.NAME }}
          fi

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%dT%H%M%S')"

    # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.RG }}
        deploymentName: azure-${{ env.NAME }}-${{ steps.date.outputs.date }}
        template: ./src/ArmTemplates/azure.json
        parameters: name=${{ env.LA_NAME }} environmentName=${{ env.NAME }}

    - uses: actions/download-artifact@master
      with:
        name: workflow
        path: ./output/

    - name: Get publish Profile
      id: publishprofile
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{ env.RG }} `
              -Name ${{ env.LA_NAME }}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest

    - name: Deploy to Azure Logic App
      uses: Azure/functions-action@v1.3.1
      id: la
      with:
        app-name: ${{ env.LA_NAME }}
        package: './output/workflow.zip'
        publish-profile: ${{steps.publishprofile.outputs.profile}}